### ISSUE TITLE
hashes for release files are missing

### ISSUE THREAD

**Issue by kdpuvvadi** [emqx/MQTTX#1318]
#### What did I do

Check for hash  in release assets

#### What happened

Not available
 
#### Expected

Available in release assets

**Comment by ysfscream** [comment]
@kdpuvvadi Hello. Thank you for reporting this issue. Based on your description, you cannot find the hashes in the release assets.

To assist you better, I would need some additional information. Could you please provide the following details:

1. From where did you download the file?
2. Which version of the package did you download?

Furthermore, I tried obtaining the hash locally, and I was able to retrieve it successfully. You can try using the following command to output the hash:

```
shasum -a 256 MQTTX-1.9.3-arm64.dmg
7ca2de45ae9b28be77dd6b02d829fbce3da71867f2c955ed7bc34497af3d1169  MQTTX-1.9.3-arm64.dmg
```

Please provide more information so I can further assist you in resolving the issue. Thank you!

**Comment by kdpuvvadi** [comment]
Hi, What i mean was to verify the hash of the file before installing as in i can see sha512 for windows set up assets but not for cli.

**Comment by ysfscream** [comment]
Could you please provide me with some additional information? For example, did you download the CLI from mqttx.app or GitHub? Also, if you don't mind, how did you obtain the sha512 after downloading? I used the following command on my macOS.
```shell
shasum -a 256 mqttx-cli-macos-arm64
842fa4a1352231c1d4f75dce08145fc8ddb7009edb306e19b35e94daa6d19f1f  mqttx-cli-macos-arm64
```
Which confirmed that the CLI is working.

**Comment by kdpuvvadi** [comment]
Okay, you guys clearly misunderstood me.  Let's say i've downloaded `mqttx-cli-win-x64.exe` from release assets. And i want to verify the integrity of that said file. I'll calculate the hash first with `Get-FileHash -Path .\mqttx-cli-win-x64.exe -Algorithm SHA256`  and compare it with the one on release page. For windows gui, `latest.yml` has `sha512`

```yaml
version: 1.9.3
files:
  - url: MQTTX-Setup-1.9.3.exe
    sha512: owo9AfJpsFnAxYhUOVQGJJhwlRiqVKvxHMwN6pZrzYkjVKq54hGHIUVG3VshMYsAnaMydOrrEs2UwIv8eV5mng==
    size: 216967716
  - url: MQTTX-Setup-1.9.3-x64.exe
    sha512: 05+6n7OgslDV+f00/L4XSxM2pbbRnOIcVshv7D4RQluHGzS2b7sht3a1fjuGZx+udecdgI1DU8ZGotVXCNeg3w==
    size: 70381065
  - url: MQTTX-Setup-1.9.3-ia32.exe
    sha512: wSpHeUz2123u3p8fTtvyu0eG6MT+7ZkbrgIe8wLuvq/tVi5wRruQhbwsqCChucKOZjqUr4JHGCnwz8ozGuK2NQ==
    size: 68056345
  - url: MQTTX-Setup-1.9.3-arm64.exe
    sha512: x4iep+aVVZRvTsEIwIgdhYlu2SD/IP2h/YgBD2RHBk2KNWWPyMCoiby2gtr8odVKUULL+sLX8wakZ1WR1RXvPA==
    size: 79709037
path: MQTTX-Setup-1.9.3.exe
sha512: owo9AfJpsFnAxYhUOVQGJJhwlRiqVKvxHMwN6pZrzYkjVKq54hGHIUVG3VshMYsAnaMydOrrEs2UwIv8eV5mng==
releaseDate: '2023-05-19T03:24:01.887Z'
```

And it's not provided for the release assets such as cli assets such as `mqttx-cli-win-x64.exe`
