### ISSUE TITLE
[Help] Connection Issues with EMQX in EKS Cluster

### ISSUE THREAD

**Issue by rakeshreddyrg09** [emqx/MQTTX#1726]
Hi Team,
I have a cluster created in EKS, components using emqx-v5.7.1, kong - using NLB
I am using mqttx to publish a message using below command
```
mqttx pub \
  --hostname mqtt.iot-test.org.com \
  --port 1883 \
  --topic devices \
  --message "{\"deviceId\":16,\"value\":40.1,\"region\":\"EMEA\",\"timestamp\":1482236627236}" \
  --username 'admin' \
  --password 'public'
```
here are the logs
```
mqttjs connecting to an MQTT broker... +0ms
  mqttjs:client MqttClient :: options.protocol mqtt +0ms
  mqttjs:client MqttClient :: options.protocolVersion 5 +0ms
  mqttjs:client MqttClient :: options.username admin +0ms
  mqttjs:client MqttClient :: options.keepalive 30 +0ms
  mqttjs:client MqttClient :: options.reconnectPeriod 1000 +0ms
  mqttjs:client MqttClient :: options.rejectUnauthorized undefined +0ms
  mqttjs:client MqttClient :: options.topicAliasMaximum undefined +0ms
  mqttjs:client MqttClient :: clientId mqttx_2ea4955d +1ms
  mqttjs:client MqttClient :: setting up stream +0ms
  mqttjs:client _setupStream :: calling method to clear reconnect +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client _setupStream :: using streamBuilder provided to client to create stream +0ms
  mqttjs calling streambuilder for mqtt +2ms
  mqttjs:tcp port 1883 and host mqtt.iot-test.org.com +0ms
  mqttjs:client _setupStream :: pipe stream to writable stream +3ms
  mqttjs:client _setupStream: sending packet `connect` +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'connect' } +1ms
  mqttjs:client sendPacket :: emitting `packetsend` +1ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqttjs:client sendPacket :: writeToStream result true +11ms
⠸ Connecting...  mqttjs:client !!connectTimeout hit!! Calling _cleanUp with force `true` +30s
  mqttjs:client _cleanUp :: forced? true +0ms
  mqttjs:client _cleanUp :: (mqttx_2ea4955d) :: destroying stream +0ms
  mqttjs:client _cleanUp :: client not disconnecting. Clearing and resetting reconnect. +1ms 
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client _setupReconnect :: emit `offline` state +0ms
  mqttjs:client _setupReconnect :: set `reconnecting` to `true` +0ms
  mqttjs:client _setupReconnect :: setting reconnectTimer for 1000 ms +0ms
  mqttjs:client (mqttx_2ea4955d)stream :: on close +0ms
  mqttjs:client flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function +0ms
  mqttjs:client stream: emit close to MqttClient +0ms
  mqttjs:client close :: connected set to `false` +0ms
  mqttjs:client close :: clearing connackTimer +0ms
  mqttjs:client close :: clearing ping timer +0ms
  mqttjs:client close :: calling _setupReconnect +0ms
  mqttjs:client _setupReconnect :: doing nothing... +0ms
⠴ Connecting...  mqttjs:client reconnectTimer :: reconnect triggered! +1s
  mqttjs:client _reconnect: emitting reconnect to client +0ms
  mqttjs:client _reconnect: calling _setupStream +0ms
  mqttjs:client _setupStream :: calling method to clear reconnect +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client _setupStream :: using streamBuilder provided to client to create stream +1ms
  mqttjs calling streambuilder for mqtt +31s
  mqttjs:tcp port 1883 and host mqtt.iot-test.org.com +31s
  mqttjs:client _setupStream :: pipe stream to writable stream +0ms
  mqttjs:client _setupStream: sending packet `connect` +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'connect' } +0ms
  mqttjs:client sendPacket :: emitting `packetsend` +1ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqttjs:client sendPacket :: writeToStream result true +0ms
  ⠏ Reconnecting...[1/10]
```
I am getting the above error.
I have creates tcpIngress as well.
```
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: mqttingress
  namespace: mqtt
  annotations:
    kubernetes.io/ingress.class: "kong-ingress"
spec:
  rules:
    - port: 1883 # MQTT port
      backend:
        serviceName: emqx
        servicePort: 1883
    - port: 8883 # MQTT SSL port
      backend:
        serviceName: emqx
        servicePort: 8883
```
Also added below config in my KONG
```
      nlbConfig: true
      proxy:
        streamPorts:
          - protocol: TCP
            containerPort: 1883
            servicePort: 1883
          # MQTT SSL Port
          - protocol: TCP
            containerPort: 8883
            servicePort: 8883
        tls:
          containerPort: 8000
```
can you team help me out here 
https://emqx.slack.com/archives/C02D74THZPF/p1721628206450979

**Comment by ieQu1** [comment]
We need to see logs from the broker side. `logs/emqx.log.*` files are of particular interest. Could you also show metrics from the broker, <broker>:18083/#/dashboard/metrics What is the value of `client.connect` metric?

**Comment by id** [comment]
@rakeshreddyrg09 it's too early to talk about MQTT or MQTTX issues. Please make sure you can establish a plain TCP connection to that endpoint and port 1883 first. It does not work for me.

```
telnet mqtt.iot-test.org.com 1883
Trying 34.206.39.153...
^C
```

**Comment by rakeshreddyrg09** [comment]
> We need to see logs from the broker side. `logs/emqx.log.*` files are of particular interest. Could you also show metrics from the broker, broker_ip:18083/#/dashboard/metrics What is the value of `client.connect` metric?
![image](https://github.com/user-attachments/assets/e7a8bd1b-ae0b-4d8e-9e6c-7ebecfe33eea)
![image](https://github.com/user-attachments/assets/52377e09-2a9b-4ca5-b2c1-f623b6c28abd)
from the above the pop is continuously coming even after providing the creds

**Comment by rakeshreddyrg09** [comment]
> @rakeshreddyrg09 it's too early to talk about MQTT or MQTTX issues. Please make sure you can establish a plain TCP connection to that endpoint and port 1883 first. It does not work for me.
> 
> ```
> telnet mqtt.iot-test.org.com 1883
> Trying 34.206.39.153...
> ^C
> ```

sorry I can't share the full address here, but I am able to connect
![image](https://github.com/user-attachments/assets/9113c470-383d-4e5c-8ae6-61b42e990b20)

**Comment by rakeshreddyrg09** [comment]
> client.connect

![image](https://github.com/user-attachments/assets/483adaf1-50e0-46e9-83d7-b640c27b4e03)

**Comment by id** [comment]
I'm not familiar with Kong ingress, but so far I think the routing is not configured correctly between NLB and EMQX, since telnet probe works, but the traffic does not reach EMQX.

Could you confirm that you have followed this guide? https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/services/tcp/

One way to troubleshoot this would be to setup an echo service on port 1883, make sure that one works, then switch back to emqx.

**Comment by rakeshreddyrg09** [comment]
here i have enabled echo service on 1883
here is my config for echo-service
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  ports:
    - port: 1883
      name: tcp
      protocol: TCP
      targetPort: 1025
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  strategy: {}
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - image: kong/go-echo:latest
          name: echo
          ports:
            - containerPort: 1025
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources: {}
---
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: echo-plaintext
  annotations:
    kubernetes.io/ingress.class: "prod-kong-ingress"
spec:
  rules:
    - port: 1883
      backend:
        serviceName: echo
        servicePort: 1883
```
below is the telnet output.
![image](https://github.com/user-attachments/assets/fa9ae039-dc3b-43b3-8d06-089cb6784961)
I am able to receive the traffic from 1883.
