### ISSUE TITLE
[Feature] Flathub deployment

### ISSUE THREAD

**Issue by eaglesemanation** [emqx/MQTTX#742]
#### Motivation

On Linux it's easy to install MQTT X through Snap store, but it adapted exclusively on Ubuntu. Meanwhile, Flatpak is distribution agnostic and installed by default on Fedora. The default repository for it is Flathub.

#### Detailed design

This will require several manifests and a pull request to flathub/flathub. I already have a [working version](https://github.com/eaglesemanation/flathub/tree/com.emqx.MQTTX), and I'm ready to do that. I would like to at the very least get an approval to do so, and at best to transfer the burden of maintaining yet another package to you.

#### Alternatives

Without support for flatpak, the only integrated way of installation for distributions which use RPM, is to manually update.

#### Additional info

Meta-info displayed in Gnome-software, just because I think pictures make anything look more legit =)
![gnome-software](https://user-images.githubusercontent.com/52473614/137573210-9bc4b152-65cb-4141-b16d-e1604de2f867.png)

**Comment by eaglesemanation** [comment]
Sorry, but that's my first experience deploying an app to Flathub, so I'm not sure myself. 

As far as I understand - when pull request to `flathub/flathub` will be accepted, they will create separate repository for the app, and give write permissions to contributor. This repository will have its own CI/CD configured, so any change to it will cause rebuild and deployment. If you want to fully automate this process, you will have to configure your own CI/CD to:
- Change `url` and `sha256` in `com.emqx.MQTTX.yaml` to point to the newest `MQTTX.AppImage`
- Add new `<release>` tag in `com.emqx.MQTTX.metainfo.xml`
- Commit it to `flathub/com.emqx.MQTTX` which will be created when accepted

Those are my assumptions, maybe there is much more convenient way of doing that

**Comment by oceanlvr** [comment]
@eaglesemanation, we now have a `CI/CD` release tool here:

https://github.com/emqx/MQTTX/tree/master/.github/workflows

I'm a fresh guy on the `github-action` & DevOps.

I mean if possible we could put the `Flathub` version release into `github-action` work-flow.

If not possible we could put your python script builder as a link on the document, so this guides those who need it to build the `Flathub` deployment version.


Looking for your next reply, THANKS!

**Comment by eaglesemanation** [comment]
@oceanlvr, I think this will work:
1. You will fork my [flathub-builder config](https://github.com/eaglesemanation/flathub/tree/com.emqx.MQTTX) and create pull request to [flathub/flathub new-pr branch](https://github.com/flathub/flathub/tree/new-pr). After that will be accepted, `flathub/com.emqx.MQTTX` repository will be created and you will have write access to it.
2. Create access token for `flathub/com.emqx.MQTTX`, so you will be able to modify it remotely using current repo `github-actions`
3. Add to your [`.github/workflows`](https://github.com/emqx/MQTTX/tree/master/.github/workflows) something along the lines of this:
```yaml
- uses: actions/checkout@v2
  if: github.event_name == 'release'
  with:
    repository: flathub/com.emqx.MQTTX
    token: ${{ secrets.GITHUB_FLATHUB_TOKEN }}
    path: flathub-repo

- name: Bump Flathub version
  run: |
    python3 $GITHUB_WORKSPACE/.github/workflows/update_version.py
    python3 $GITHUB_WORKSPACE/.github/workflows/update_releases.py

- uses: EndBug/add-and-commit@v7
  if: github.event_name == 'release'
  with:
    cwd: ./flathub-repo
```
I have no experience with github actions, so I'm not sure if steps 2 and 3 are going to work.
